= **CREDIT CARD SERVICE ON FLUTTER**

== **DESCRIPTION**

The *Flutter YOLO Credit Card Extractor* is a mobile applicacion developed in Flutter for *Android* that allow detection and data extraction from credit or debit card from a picture. It uses advanced object detection algorithms and AI-assisted text recognition.

This app allow to made all process in the same device uses *YOLOv8* or throuhg API Rest with *YOLOv10*.

* Credit card detection using YOLO models.
* Text extraction such as card numbers, cardholder name and expiration date using Google ML Kit.
* Simple and attractive user interface.


- [Lab: Write your first Flutter app](https://docs.flutter.dev/get-started/codelab)
- [Cookbook: Useful Flutter samples](https://docs.flutter.dev/cookbook)

== **TECHNOLOGIES**

image:https://badges.aleen42.com/src/github.svg[]
image:https://badges.aleen42.com/src/visual_studio_code.svg[]
image:https://badges.aleen42.com/src/tensorflow.svg[]
image:https://img.shields.io/badge/Dart-0175C2?style=flat&logo=dart&logoColor=white[]
image:https://img.shields.io/badge/Flutter-%2302569B.svg?style=for-the-badge&logo=Flutter&logoColor=white[]
image:https://img.shields.io/badge/github_copilot-8957E5?style=for-the-badge&logo=github-copilot&logoColor=white[]
image:https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white[]

* Flutter 3.27
* Dart SDK
* Visual Studio Code
* Gradle version 7.1.2
* Kotlin version 1.7.10
* Flutter Vision
* BLoC
* Google ML Kit Text Recognition


== **Project Structure**
[listing, tree]
----
├── android/
├── assets/
├── build/
├── ios/
├── lib/
├── linux/
├── macos/
├── test/
├── web/
├── windows/
├── pubspec.lock
├── pubspec.yaml
└── README.adoc
----


## Getting Started

1. **Clone this repository**

```bash
   git clone https://github.com/nahueltabasso/yolo_flutter_creditcard.git
   cd flutter_yolo_creditcard
```

2. **Install dependencies**

First, checked that you have Flutter installed and execute the next command:

```bash
    flutter pub get
```

3. Before to run this app, need to modify a source code of a `flutter_vision` library

```bash
    cd ~/.pub-cache/hosted/pub.dev/flutter_vision-1.1.4/android
    nano build.gradle
```

After open that file, add this `namespace "com.vladih.computer_vision.flutter_vision"`

```bash
    android {
        namespace "com.vladih.computer_vision.flutter_vision"
        compileSdkVersion 31
    }
```

4. **Execute the app**

Connect a device or open an emulator, and run:
```bash
    flutter run
```

== **How to use it!**


== **License**

This project is licensed under the MIT License - see the LICENSE file for details.
